# ESS设置
eta_ess = 0.95
ess_level_init = 1.80
ess_level_max = 6.0
ess_level_min = 0.6
ess_aging_cost = 0.001
p_ess_max = 3
# HVAC/温度设置
p_hvac_max = 2
T_min = 66.2
T_max = 75.6
beta_hvac = 1
epsilon_hvac = 0.7
eta_hvac = 2.5
A_hvac = 0.14
temp_indoor_init = 73.4
# 数据加载路径
solar_data_path = "data/solar_double.csv"
load_data_path = "data/base_load_modified.csv"
temp_outdoor_data_path = "data/temp_modified.csv"
price_data_path = "data/price_modified.csv"
# 日期设置
day_init = 0
day_duration = 61
# 卖电/购电价格比例
price_ratio = 0.9
